### PR TITLE
Reorganization to better support prefixes, remove dead code, fix StringBuilder issues, and improve code coverage testing

### LINKED ISSUE #26: VerifyError when methods called on named expressions return values
Attempting to invoke methods on the return value of a named expression results in a `VerifyError`. An example is that the template `{{returnArg -> .}}{{returnArg("123").replace("1", "2")}}` fails. See e55eec6 for a functional test that tests this. 

Here is the relevant stacktrace:
```
java.lang.VerifyError: (class: horseshoe/internal/dyn/Expression_1, method: evaluate signature: ([Lhorseshoe/internal/Expression;[Lhorseshoe/internal/Identifier;Lhorseshoe/internal/PersistentStack;Lhorseshoe/Settings$ContextAccess;Lhorseshoe/internal/PersistentStack;Lhorseshoe/Settings$ErrorLogger;)Ljava/lang/Object;) Incompatible object argument for function call
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
	at java.base/java.lang.Class.getConstructor0(Class.java:3343)
	at java.base/java.lang.Class.getConstructor(Class.java:2152)
	at horseshoe.internal.Expression.<init>(Expression.java:890)
```

### PR DESCRIPTION
**Pull request by nicklauslittle**
Closes #26, #22.

### CODE REVIEW

File: src/test/java/horseshoe/NamedExprTests.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+		final Template template = new TemplateLoader()
+				.load("Test", "{{returnArg -> .}}{{(returnArg(\"123\") + \"4\").`replace:CharSequence`(\"1\", \"2\")}}");
+		final StringWriter writer = new StringWriter();
+		template.render(settings, Collections.emptyMap(), writer);
+		assertEquals("2234", writer.toString());
+	}
+
+	@Test
+	public void testNamedExpressions() throws IOException, LoadException {
+		assertEquals("ORIGINAL STRING-Original string" + LS, new TemplateLoader().load("Upper", "{{upper->toUpperCase()}}\n{{capitalize=>substring(0, 1).toUpperCase() + substring(1).toLowerCase()}}\n{{#\"orIgInal StrIng\"}}\n{{#charAt(1)}}\n{{upper(..)}}-{{capitalize(..)}}\n{{/}}\n{{/}}").render(new Settings(), Collections.emptyMap(), new StringWriter()).toString());
```
Comment (tbateson) [inline src/test/java/horseshoe/NamedExprTests.java]: Why are there different syntaxes (`->` and `=>`) for declaring named expressions?

File: src/test/java/horseshoe/TemplateTests.java [hunk 2]
```diff
@@ -86,6 +80,11 @@ public void write(final char[] arg0, final int arg1, final int arg2) throws IOEx
 		});
 	}
 
+	@Test
+	public void testRootIdentifiers() throws IOException, LoadException {
+		assertEquals("Root Local Root Root", new TemplateLoader().load("Root", "{{#[\"Value\":\"Local\"]}}{{\\Value}} {{Value}} {{ /Value }}{{#/.}} {{Value}}{{/}}{{/}}").render(new Settings(), Collections.singletonMap("Value", "Root"), new java.io.StringWriter()).toString());
```
Comment (tbateson) [inline src/test/java/horseshoe/TemplateTests.java]: Let's add an extension enumeration for this feature, I can imagine it being confusing how `{{ /Value}}` is different from `{{/Value}}` in terms of parsing.

File: src/test/java/horseshoe/NamedExprTests.java (hunk 1 above)
Comment (nicklauslittle) [reply src/test/java/horseshoe/NamedExprTests.java]: The goal was to use something that looked like lambda syntax and different languages use both syntax forms.

File: src/test/java/horseshoe/TemplateTests.java (hunk 2 above)
Comment (nicklauslittle) [reply src/test/java/horseshoe/TemplateTests.java]: This is one reason I introduced the backslash as an alternative to the forward slash.

Are you thinking something like a "treat unmatched close tags as stand-alone expressions" extension? Or maybe an explicit character after `{{` for expressions? Both? Something else?

Comment (tbateson) [reply src/test/java/horseshoe/TemplateTests.java]: How is `{{ #key }}` supposed to be parsed according to the mustache spec? Is it equivalent to `{{#key}}`? Is it not equivalent? Does it say anything about it?

File: src/test/java/horseshoe/NamedExprTests.java (hunk 1 above)
Comment (tbateson) [reply src/test/java/horseshoe/NamedExprTests.java]: Given that horseshoe is a Java focused language, I think that using only the java syntax for lambdas `name -> expr(s)` is sufficient. Having multiple forms that a developer can use leads to inconsistencies (I'm thinking how C# has `string` vs `String` that necessitate coding standards.

File: src/test/java/horseshoe/TemplateTests.java (hunk 2 above)
Comment (nicklauslittle) [reply src/test/java/horseshoe/TemplateTests.java]: That is an excellent question. The mustache spec, as far as I can tell, is mute on the point. All the examples and tests do not have any spaces between the opening curly braces and the tag contents.

However, there are multiple tests in the mustache spec that have things like `{{# key }}` with comments that say `Superfluous in-tag whitespace should be ignored.` This leads me to believe the intention is that the character after the opening curly braces is used to determine how the tag is parsed.

Comment (tbateson) [reply src/test/java/horseshoe/TemplateTests.java]: I almost prefer using `..\` for referring to higher-level scope and `\` to refer to root-level scope. This way there won't be any ambiguity about what `{{ /Value }}` means.

Comment (nicklauslittle) [reply src/test/java/horseshoe/TemplateTests.java]: It's not really ambiguous, just that the ruleset governing how `{{/` is parsed is more complicated than the other tags.

I definitely agree that using `\` and `..\` should be preferred to `/` and `../` for clarity, but I definitely think that there will be those who want to use the forward slash.

Comment (tbateson) [reply src/test/java/horseshoe/TemplateTests.java]: My above comment on `->` vs `=>` still stands, although in this case I think it's far more problematic since in this case the `/` character is already reserved for closing sections.

Comment (nicklauslittle) [reply src/test/java/horseshoe/TemplateTests.java]: I agree with the comment, but I don't think supporting both syntax forms is bad.

I added an extension that supports smart determination of the meaning of `{{/` tags. See the latest changes for details.
